### ISSUE TITLE
Cannot notarize libgdx app built with JPackage on OS X

### ISSUE THREAD

**Issue by soundasleep** [libgdx/libgdx#7011]
#### Issue details

I'm brand new to OS X deployment and it's frustrating to say the least, so I'm sorry if I'm missing something obvious!

Through a ton of hacking and debugging I've managed to get JPackage to build, and successfully sign, my libgdx project as a `.dmg`. Apple still refuses to run it, though, so I'm trying to [get the `.dmg` notarised](https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution), which will eventually be required for _all_ MacOS applications it seems.

Eventually I got a reply from the notarization server:

```json
{
  "logFormatVersion": 1,
  "jobId": "xxx",
  "status": "Invalid",
  "statusSummary": "Archive contains critical validation errors",
  "statusCode": 4000,
  "archiveFilename": "archive.zip",
  "uploadDate": "2022-10-17T08:43:43Z",
  "sha256": "xxx",
  "ticketContents": null,
  "issues": [
    {
      "severity": "error",
      "code": null,
      "path": "archive.zip/package/DesktopLauncher.dmg/DesktopLauncher.app/Contents/app/dependencies/gdx-box2d-platform-1.10.0-natives-desktop.jar/libgdx-box2d64.dylib",
      "message": "The binary is not signed.",
      "docUrl": "https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution/resolving_common_notarization_issues#3087721",
      "architecture": "x86_64"
    },
    {
      "severity": "error",
      "code": null,
      "path": "archive.zip/package/DesktopLauncher.dmg/DesktopLauncher.app/Contents/app/dependencies/gdx-box2d-platform-1.10.0-natives-desktop.jar/libgdx-box2d64.dylib",
      "message": "The signature does not include a secure timestamp.",
      "docUrl": "https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution/resolving_common_notarization_issues#3087733",
      "architecture": "x86_64"
    },
    {
      "severity": "error",
      "code": null,
      "path": "archive.zip/package/DesktopLauncher.dmg/DesktopLauncher.app/Contents/app/dependencies/gdx-box2d-platform-1.10.0-natives-desktop.jar/libgdx-box2d64.dylib",
      "message": "The binary is not signed with a valid Developer ID certificate.",
      "docUrl": "https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution/resolving_common_notarization_issues#3087721",
      "architecture": "arm64"
    },
    {
      "severity": "error",
      "code": null,
      "path": "archive.zip/package/DesktopLauncher.dmg/DesktopLauncher.app/Contents/app/dependencies/gdx-box2d-platform-1.10.0-natives-desktop.jar/libgdx-box2d64.dylib",
      "message": "The signature does not include a secure timestamp.",
      "docUrl": "https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution/resolving_common_notarization_issues#3087733",
      "architecture": "arm64"
    },
    {
      "severity": "error",
      "code": null,
      "path": "archive.zip/package/DesktopLauncher.dmg/DesktopLauncher.app/Contents/app/dependencies/gdx-freetype-platform-1.10.0-natives-desktop.jar/libgdx-freetype64.dylib",
      "message": "The binary is not signed.",
      "docUrl": "https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution/resolving_common_notarization_issues#3087721",
      "architecture": "x86_64"
    },
    {
      "severity": "error",
      "code": null,
      "path": "archive.zip/package/DesktopLauncher.dmg/DesktopLauncher.app/Contents/app/dependencies/gdx-freetype-platform-1.10.0-natives-desktop.jar/libgdx-freetype64.dylib",
      "message": "The signature does not include a secure timestamp.",
      "docUrl": "https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution/resolving_common_notarization_issues#3087733",
      "architecture": "x86_64"
    },
    {
      "severity": "error",
      "code": null,
      "path": "archive.zip/package/DesktopLauncher.dmg/DesktopLauncher.app/Contents/app/dependencies/gdx-freetype-platform-1.10.0-natives-desktop.jar/libgdx-freetype64.dylib",
      "message": "The binary is not signed with a valid Developer ID certificate.",
      "docUrl": "https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution/resolving_common_notarization_issues#3087721",
      "architecture": "arm64"
    },
    {
      "severity": "error",
      "code": null,
      "path": "archive.zip/package/DesktopLauncher.dmg/DesktopLauncher.app/Contents/app/dependencies/gdx-freetype-platform-1.10.0-natives-desktop.jar/libgdx-freetype64.dylib",
      "message": "The signature does not include a secure timestamp.",
      "docUrl": "https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution/resolving_common_notarization_issues#3087733",
      "architecture": "arm64"
    },
    {
      "severity": "error",
      "code": null,
      "path": "archive.zip/package/DesktopLauncher.dmg/DesktopLauncher.app/Contents/app/dependencies/gdx-platform-1.10.0-natives-desktop.jar/libgdx64.dylib",
      "message": "The binary is not signed.",
      "docUrl": "https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution/resolving_common_notarization_issues#3087721",
      "architecture": "x86_64"
    },
    {
      "severity": "error",
      "code": null,
      "path": "archive.zip/package/DesktopLauncher.dmg/DesktopLauncher.app/Contents/app/dependencies/gdx-platform-1.10.0-natives-desktop.jar/libgdx64.dylib",
      "message": "The signature does not include a secure timestamp.",
      "docUrl": "https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution/resolving_common_notarization_issues#3087733",
      "architecture": "x86_64"
    },
    {
      "severity": "error",
      "code": null,
      "path": "archive.zip/package/DesktopLauncher.dmg/DesktopLauncher.app/Contents/app/dependencies/gdx-platform-1.10.0-natives-desktop.jar/libgdx64.dylib",
      "message": "The binary is not signed with a valid Developer ID certificate.",
      "docUrl": "https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution/resolving_common_notarization_issues#3087721",
      "architecture": "arm64"
    },
    {
      "severity": "error",
      "code": null,
      "path": "archive.zip/package/DesktopLauncher.dmg/DesktopLauncher.app/Contents/app/dependencies/gdx-platform-1.10.0-natives-desktop.jar/libgdx64.dylib",
      "message": "The signature does not include a secure timestamp.",
      "docUrl": "https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution/resolving_common_notarization_issues#3087733",
      "architecture": "arm64"
    }
  ]
}
```

Could it be the case that some of the `.dylib` files (executable/DLLs) aren't being signed in `gdx-platform-xxx-native-desktop.jar`, and that's causing notarization to fail? If so, is this a known issue? Would upgrading to 1.11 help? I don't see anything about signing/notarization in [the 1.11 changelog](https://libgdx.com/news/2022/05/gdx-1-11).

Alternatively, I'm wondering if a workaround could be to specifically sign the .dylibs in the dependency .jars before packaging, perhaps everything in `/desktop/build/libs/dependencies/*.jar`, but that sounds like a bad idea, considering signed Java .jars [don't want to be modified](https://docs.oracle.com/javase/tutorial/deployment/jar/signindex.html)...

#### Reproduction steps/code

I'm using GitHub actions with something similar to:

```yaml
    - name: Package with jpackage
      run: ./gradlew jpackage --info

    - name: "Notarize Release Build"
      uses: devbotsxyz/xcode-notarize@v1
      with:
        product-path: ${{ github.workspace }}/desktop/build/package/DesktopLauncher-10.1.2.dmg
        appstore-connect-username: ${{ secrets.NOTARIZATION_USERNAME }}
        appstore-connect-password: ${{ secrets.NOTARIZATION_PASSWORD }}
        primary-bundle-id: org.jevon.my.package
```

#### Version of libGDX and/or relevant dependencies

- libgdx 1.10
- [org.panteleyev:jpackage-gradle-plugin](https://github.com/petr-panteleyev/jpackage-gradle-plugin) 1.3.1

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [x] macOS

**Comment by Berstanio** [comment]
You probably need to codesign them yourself.
As far as I'm aware the you need to sign it with the same Developer ID as you want to notarize it, so I don't think that can be fixed on libGDX side.

**Comment by soundasleep** [comment]
Thank you! Yes, it looks like extracting & signing the .dylibs themselves are the best solution, at least for now. If the native .jars are ever signed in the future (`jarsigner`?), I'd expect libgdx might need to do the codesigning.

Based on https://stackoverflow.com/a/61091234/39531 I basically have this in my GitHub Actions, sharing here in case it helps anyone else:

```yaml
- name: Set up signing files
  env:
    KEYCHAIN_PATH: ${{ runner.temp }}/app-signing.keychain-db
    DEVELOPER_ID_APPLICATION_NAME: Your Company Here (ABC1234567)
  run: |
    # based on https://stackoverflow.com/a/70991269/39531
    echo -n '${{ secrets.SIGN_APPLICATION_P12 }}' | base64 --decode > certificate_application.p12
    echo -n '${{ secrets.SIGN_INSTALLER_P12 }}' | base64 --decode > certificate_installer.p12

    security create-keychain -p "${{ secrets.KEYCHAIN_PASSWORD }}" $KEYCHAIN_PATH
    security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
    security unlock-keychain -p "${{ secrets.KEYCHAIN_PASSWORD }}" $KEYCHAIN_PATH

    security import certificate_application.p12 -P "${{ secrets.KEYCHAIN_PASSWORD }}" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
    security import certificate_installer.p12 -P "${{ secrets.KEYCHAIN_PASSWORD }}" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
    echo $KEYCHAIN_PATH
    security list-keychain -d user -s $KEYCHAIN_PATH

    # test that we can use codesign correctly
    echo hi > hi.txt
    codesign -vvv --force --sign "Developer ID Application: $DEVELOPER_ID_APPLICATION_NAME" hi.txt
    codesign -vvv --verify hi.txt

- name: Build with Gradle
  run: ./gradlew build --info

- name: Checkout dependencies so we can extract .dylibs from them
  run: ./gradlew dist --info

- name: Re-sign .dylibs inside .jars for notarization
  env:
    DEVELOPER_ID_APPLICATION_NAME: Your Company Here (ABC1234567)
  run: |
    # there's probably a way to use 'find' to do this, but copy-paste will be fine for now

    jar xf ${{ github.workspace }}/desktop/build/libs/dependencies/gdx-box2d-platform-1.10.0-natives-desktop.jar/ libgdx-box2d64.dylib
    codesign -vvv --force --sign "Developer ID Application: $DEVELOPER_ID_APPLICATION_NAME" libgdx-box2d64.dylib
    jar uf ${{ github.workspace }}/desktop/build/libs/dependencies/gdx-box2d-platform-1.10.0-natives-desktop.jar/ libgdx-box2d64.dylib
    rm libgdx-box2d64.dylib

    jar xf ${{ github.workspace }}/desktop/build/libs/dependencies/gdx-freetype-platform-1.10.0-natives-desktop.jar/ libgdx-freetype64.dylib
    codesign -vvv --force --sign "Developer ID Application: $DEVELOPER_ID_APPLICATION_NAME" libgdx-freetype64.dylib
    jar uf ${{ github.workspace }}/desktop/build/libs/dependencies/gdx-freetype-platform-1.10.0-natives-desktop.jar/ libgdx-freetype64.dylib
    rm libgdx-freetype64.dylib

    jar xf ${{ github.workspace }}/desktop/build/libs/dependencies/gdx-platform-1.10.0-natives-desktop.jar/ libgdx64.dylib
    codesign -vvv --force --sign "Developer ID Application: $DEVELOPER_ID_APPLICATION_NAME" libgdx64.dylib
    jar uf ${{ github.workspace }}/desktop/build/libs/dependencies/gdx-platform-1.10.0-natives-desktop.jar/ libgdx64.dylib
    rm libgdx64.dylib

- name: Package with jpackage
  env:
    DEVELOPER_ID_APPLICATION_NAME: Your Company Here (ABC1234567)
    KEYCHAIN_PATH: ${{ runner.temp }}/app-signing.keychain-db
    JPACKAGE_TYPE: dmg
  run: SKIP_JPACKAGE_DIST=1 ./gradlew jpackage --info

- name: Rename .dmg to a constant filename
  run: |
    mv ${{ github.workspace }}/desktop/build/package/*.dmg ${{ github.workspace }}/desktop/build/package/DesktopLauncher.dmg
    ls -la ${{ github.workspace }}/desktop/build/package/

- name: Notarize Release Build # NOTE this task can take ~20 minutes to run, it blocks until successful
  uses: devbotsxyz/xcode-notarize@v1
  with:
    product-path: ${{ github.workspace }}/desktop/build/package/DesktopLauncher.dmg
    appstore-connect-username: ${{ secrets.NOTARIZATION_USERNAME }}
    appstore-connect-password: ${{ secrets.NOTARIZATION_PASSWORD }}
    primary-bundle-id: org.your.bundle.package
    verbose: true

- name: Staple Release Build
  uses: devbotsxyz/xcode-staple@v1
  with:
    product-path: ${{ github.workspace }}/desktop/build/package/DesktopLauncher.dmg
    verbose: true
```
